### ISSUE TITLE
cmvnw: Division by zero

### ISSUE THREAD

**Issue by thomasZen** [astorfi/speechpy#10]
In encountered the following warning during the variance normalization of the speech features:

> RuntimeWarning: divide by zero encountered in true_divide

[cmvnw](https://github.com/astorfi/speechpy/blob/master/speechpy/processing.py#L239
)
This is probably not the desired behavior, I don't know what the best solution in this case is though.

**Comment by astorfi** [comment]
Can you send me the code and the files that you are trying to extract the features from?

**Comment by astorfi** [comment]
In your provided example, the variance is zero!! So it returns nan obviously. I am a little bit confused!

**Comment by thomasZen** [comment]
After performing variance normalization you should return a vector that has unit variance. That's not possible in this example without changing the properties of the vector. But I would still try to avoid dividing by zero. At least when training a neural network you want to avoid having NAN values in your feature vector.
Would it be possible to set the calculated variance to a minimum value, for example with doing the following:
`window_variance = np.maximum(window_variance, np.finfo(np.float32).eps)`
This would at least avoid dividing the vector by zero and (if I understood it correctly) is also the way kaldi handles this situation.

**Comment by astorfi** [comment]
@thomasZen Thanks for point it out. I will try to hit the root problem and provide a better solution.

**Comment by astorfi** [comment]
@thomasZen The problem has been resolved! Please check and give your feedback here.
Thanks
