### ISSUE TITLE
A typo in documentation

### ISSUE THREAD

**Issue by ReeRay** [astorfi/speechpy#12]
In [test page](http://speechpy.readthedocs.io/en/latest/epilogue/test.html) of doc, a param `Filter` in `speechpy.processing.stack_frames` should be `filter` which has fixed in the latest code in [`package`](https://github.com/astorfi/speechpy/blob/master/tests/test_package.py#L14) and [`local`](https://github.com/astorfi/speechpy/blob/master/tests/test_local.py#L19).

**Comment by astorfi** [comment]
@ReeRay Thank you so much for declaring that.
It will be considered and modified!
