### ISSUE TITLE
Correct wav format?

### ISSUE THREAD

**Issue by taewookim** [astorfi/speechpy#14]
Im trying to extract mfcc features from audio of a video file.

I tried FFMPEG:

```
def extractAudioFromVideo(video, audio_out="out.wav"):
	cmd="ffmpeg -i {} -acodec pcm_s16le -ac 1 -ar 16000 {}".format(video, audio_out)
	os.system(cmd)
	return audio_out

def extractAudioMFCC(file_name="out.wav"):
	fs, signal = wav.read(file_name)
	signal = signal[:,0]

	############# Extract MFCC features #############
	mfcc = speechpy.feature.mfcc(signal, sampling_frequency=fs, frame_length=0.020, frame_stride=0.01,num_filters=40, fft_length=512, low_frequency=0, high_frequency=None)
	mfcc_cmvn = speechpy.processing.cmvnw(mfcc,win_size=301,variance_normalization=True)
	print('mfcc(mean + variance normalized) feature shape=', mfcc_cmvn.shape)


extractAudioMFCC("test.mp4", audio_out="out.wav")
extractAudioMFCC("out.wav")

````

The error I get:

> Traceback (most recent call last):
>   File "TWK.py", line 99, in <module>
>     extractAudioMFCC()
>   File "TWK.py", line 22, in extractAudioMFCC
>     signal = signal[:,0]
> IndexError: too many indices for array

Am I using the wrong wav format?

**Comment by astorfi** [comment]
Would you please tell me why you are using signal[:,0] format?
The error does not seem to come from the package. It's a pythonic mismatch. In the test example of this repository, the reason behind using **signal[:,0]** is the dual-band nature of the example Wav files. Yours may only have a single channel. Try to remove signal = signal[:,0] and run the code again.

**Comment by taewookim** [comment]
hey @astorfi . Ah, you were right.. i was blindly copy pasting the tutorial code and i completely forgot to check the shape. Thank you

Apologies in advance but im new to audio processing. I'm trying [to do this in syncet](https://github.com/voletiv/syncnet-in-keras/issues/1), where the audio inputs are mfcc features and the audio model takes this input (according to model.summary())

> conv1_audio (Conv2D)         (None, 13, 20, 64)        640


According to the owner of syncnet repo, 


> I have used a library called speechpy to extract MFCC features. The function to extract MFCC features from a .wav file according to the instructions using speechpy is:
> 
> speechpy.feature.mfcc(signal, sampling_frequency, frame_length=0.010, frame_stride=0.010, num_cepstral=13)
> Audio features are computed over a duration of audio. In the paper, it is mentioned that features are computed at 100 Hz => for every 0.010 seconds. Hence, frame_length=0.010, frame_stride=0.010 (no overlap).
> 
> According to the paper, audio features and video features are extracted for every 0.2 seconds.
> Lip: 0.2 seconds => 0.2 * 25fps = 5 video frames
> Audio: 0.2 seconds => 0.2 / 0.01(frame duration) = 20 audio frames
> 
> Hence, a 112x112x5 matrix is input to the lips model, and a 13x20 matrix is input to the audio model.
 
Can you help me understand how to shape peechpy.feature.mfcc return value to be 13x20 matrix?
