### ISSUE TITLE
filter bank shape

### ISSUE THREAD

**Issue by ab37695543xs** [astorfi/speechpy#17]
Hi, I found that in your  `feature.py` line 44:
```
# Initial definition
    filterbank = np.zeros([num_filter, fftpoints])

    # The triangular function for each filter
    for i in range(0, num_filter):
        left = int(freq_index[i])
        middle = int(freq_index[i + 1])
        right = int(freq_index[i + 2])
        z = np.linspace(left, right, num=right - left + 1)
        filterbank[i, left:right + 1] = functions.triangle(z, left=left, middle=middle, right=right)

    return filterbank
```
You use `fftpoints` directly to initialize, but as you use 512 as default, I think it should be 257 corresponding to FFT results.
I also checked other libraries such as `python_speech_features` and `librosa`, they all make it `NFFT//2 + 1`.
I just want to make sure the differences, thanks.

**Comment by astorfi** [comment]
@ab37695543xs Thank you for pointing it out. I will further investigate it.
Thanks

**Comment by astorfi** [comment]
@ab37695543xs  I investigated this case. Actually, there is no mistake and **NFFT//2 + 1** is still the same. However, the naming convention was confusing. I just changed it for clarification. ``fftpoints`` has not actually been used for initialization. In the library, it will be superseded by the correct number.
Please let me know if you had any further question and reopen this issue if still, you had any problem regarding this.
