### ISSUE TITLE
MFCC Feature 

### ISSUE THREAD

**Issue by ranjal** [astorfi/speechpy#31]
Respected Sir,
Greetings of the day !!!

Sir first of all thank you so much for such amazing library you shared with us.

Sir I am using SpeechPy library for extracting the MFCC of audio signal.

Sir I have an audio signal of 16kHz, 32bit float PCM, Mono channel. I am using framelength 100ms with 50% overlapping.

I used below code for extraction of MFCC,

fs, signal = wav.read("b0.wav")
signal = signal / abs(max(signal)) #Convert into double
mfcc = speechpy.feature.mfcc (signal , sampling_frequency=fs, frame_length=0.1, frame_stride=0.05, num_filters=40, fft_length=2048, low_frequency=0, high_frequency=None)

Respected Sir, I got confusion because I used python_speech_features library also to extract mfcc and for verification of my result. But both are giving different result.

mfcc1 = python_speech_features.base.mfcc(signal, samplerate=fs, winlen=0.1, winstep=0.05, numcep=13, nfilt=26, nfft=2048, lowfreq=0, highfreq=None, preemph=0.97, ceplifter=22, appendEnergy=True)

I wanted to know where I am doing mistake.

My Questions Are:

1) Is the above code sequence is correct to extract mfcc using speechpy library ?

2) While using speechpy.feature.mfcc function,  preemphasis operation is not performed? That is the reason both library are giving different result.

Should we have to perform seprately preemphasis using below code then we have to give the output of preemphasis to mfcc?

signal_preemphasized = speechpy.processing.preemphasis(signal, cof=0.98)

3) Why both library are giving different result ?

Its my humble request respected Sir Please response to my query. I am not getting clarification. What to use and which is correct.

I am sorry for my poor English.

**Comment by MatthewScholefield** [comment]
1. It looks correct to me.
2. It is correct that it is not performed by default. That's probably not the only reason they are different.
3. There are a few reasons they could be different:
 - Your number of filters dont match between the two
 - The default high frequencies between the libraries could be different
 - I don't think speechpy performs any cepstrum lifting by default

Anyways, it would probably be more helpful to try visualizing the MFCC features to compare them qualitatively (using something like [arriz](https://github.com/mycroftai/arriz)). There could also be small calculation differences depending on what fft implementation the other library uses. Beyond that, you can look into the source code of each library to compare any subtle calculation differences.

**Comment by ranjal** [comment]
Thankyou so much @MatthewScholefield for your kind response.
