### ISSUE TITLE
Extracting log mel filterbank features

### ISSUE THREAD

**Issue by bluemonk482** [astorfi/speechpy#32]
Thanks very much for the great library! It's my default library for speech processing now.

Just want to double check on the following, I want to extract 40-dimensional log mel filterbank feautres from sliding a Hamming window of width 25ms with an overlap of 10ms. Does the code below extract the right features? I am a bit uncertain whether `frame_stride=0.01` creates overlap of 10ms..

```
fs, signal = wav.read(file_path)
lmfe = speechpy.feature.lmfe(signal, sampling_frequency=fs, frame_length=0.025, frame_stride=0.01, num_filters=40, fft_length=512, low_frequency=0, high_frequency=None)
```

Thanks!

**Comment by MichelleYang2017** [comment]
I suggest that you should read some source code:
>> frame_stride (float): the step between successive frames in seconds.
So,frame_stride means that no overlap
