### ISSUE TITLE
pre-emphasis

### ISSUE THREAD

**Issue by stefbraun** [astorfi/speechpy#6]
Hi, it seems that pre-emphasis is not implemented. Will you add this in the future?

**Comment by astorfi** [comment]
Thank you so much for pointing it out. It used to be part of the package but due to some technical issues, it's been eliminated. Yes, I have plans to add it in the future and pull requests are also welcome. Once again, thank you so much for your attention.

**Comment by astorfi** [comment]
@stefbraun The pre-emphasis has been added. Please refer to [processing function](https://github.com/astorfi/speechpy/blob/master/speechpy/processing.py).

Thank you so much for your declared issue.
Bests
